# indexing and selecting data

[xarray doc](http://xarray.pydata.org/en/stable/indexing.html#)


In [3]:
import xarray as xr
import numpy as np

In [17]:
v1 = xr.DataArray(np.arange(5*8).reshape((5, 8)), dims={'x':np.arange(8),'y':np.arange(5)},name='v1')
v2 = xr.DataArray(np.ones((5, 8)), dims={'x':np.arange(0,9),'y':np.arange(5)},name='v2')
print v1
print v2
print (v1+v2).rename('v1+v2')


<xarray.DataArray 'v1' (y: 5, x: 8)>
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])
Dimensions without coordinates: y, x
<xarray.DataArray 'v2' (y: 5, x: 8)>
array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])
Dimensions without coordinates: y, x
<xarray.DataArray 'v1+v2' (y: 5, x: 8)>
array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.]])
Dimensions without coordinates: y, x
