# indexing and selecting data

From [xarray doc](http://xarray.pydata.org/en/stable/indexing.html#) :

<table>
<col width="18%" />
<col width="14%" />
<col width="33%" />
<col width="33%" />
<thead>
<tr class="header">
<th align="left">Dimension lookup</th>
<th align="left">Index lookup</th>
<th align="left"><code>DataArray</code> syntax</th>
<th align="left"><code>Dataset</code> syntax</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Positional</td>
<td align="left">By integer</td>
<td align="left"><code>arr[:, 0]</code></td>
<td align="left"><em>not available</em></td>
</tr>
<tr class="even">
<td align="left">Positional</td>
<td align="left">By label</td>
<td align="left"><code>arr.loc[:, 'IA']</code></td>
<td align="left"><em>not available</em></td>
</tr>
<tr class="odd">
<td align="left">By name</td>
<td align="left">By integer</td>
<td align="left"><code>arr.isel(space=0)</code> or <code>arr[dict(space=0)]</code></td>
<td align="left"><code>ds.isel(space=0)</code> or <code>ds[dict(space=0)]</code></td>
</tr>
<tr class="even">
<td align="left">By name</td>
<td align="left">By label</td>
<td align="left"><code>arr.sel(space='IA')</code> or <code>arr.loc[dict(space='IA')]</code></td>
<td align="left"><code>ds.sel(space='IA')</code> or <code>ds.loc[dict(space='IA')]</code></td>
</tr>
</tbody>
</table>


In [1]:
import xarray as xr
import numpy as np

In [26]:
# automatic alignment subset data
nx, ny = 3, 4
v1 = xr.DataArray(np.arange(nx*ny).reshape((nx, ny)), \
                  coords={'x':.5+np.arange(nx),'y':np.arange(ny)},dims=['x','y'],name='v1')
print v1
v2 = xr.DataArray(np.ones((nx, ny+2)), coords={'x':.5+np.arange(nx),'y':np.arange(ny+2)},dims=['x','y'],name='v2')
print v2
print (v1+v2).rename('v1+v2')

<xarray.DataArray 'v1' (x: 3, y: 4)>
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
Coordinates:
  * y        (y) int64 0 1 2 3
  * x        (x) float64 0.5 1.5 2.5
<xarray.DataArray 'v2' (x: 3, y: 6)>
array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])
Coordinates:
  * y        (y) int64 0 1 2 3 4 5
  * x        (x) float64 0.5 1.5 2.5
<xarray.DataArray 'v1+v2' (x: 3, y: 4)>
array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])
Coordinates:
  * y        (y) int64 0 1 2 3
  * x        (x) float64 0.5 1.5 2.5


In [27]:
# redindexing fill with NaN when expanding
print v1.reindex_like(v2)

<xarray.DataArray 'v1' (x: 3, y: 6)>
array([[  0.,   1.,   2.,   3.,  nan,  nan],
       [  4.,   5.,   6.,   7.,  nan,  nan],
       [  8.,   9.,  10.,  11.,  nan,  nan]])
Coordinates:
  * y        (y) int64 0 1 2 3 4 5
  * x        (x) float64 0.5 1.5 2.5


In [29]:
# shift indexes and ignore alignment
v3 = v1
v3['y']=v3['y']+1
print v3


<xarray.DataArray 'v1' (x: 3, y: 4)>
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
Coordinates:
  * y        (y) int64 2 3 4 5
  * x        (x) float64 0.5 1.5 2.5
